### ISSUE TITLE
slider_plotly.ipynb is empty

### ISSUE THREAD

**Issue by Chia-vie** [Chia-vie/Group-34#5]
Hi Laura, I'm afraid slider_plotly.ipynb is empty. Can you look in your local version of your plotter branch again?

**Comment by lketzer** [comment]
It should be fixed now. also the same code is in sliderplot.py because for me in the VS jupyter notebook it is extremely slow.

**Comment by lketzer** [comment]
It should be fixed now. also the same code is in sliderplot.py because for me in the VS jupyter notebook it is extremely slow.

**Comment by Chia-vie** [comment]
Great =)
